"""
Markdown Formatter Adapter

This adapter formats structured answers into markdown reports.
Creates user-friendly output with citations, headers, and formatting.

TO IMPLEMENT:
1. Convert StructuredAnswer to markdown
2. Add citations and source links
3. Format with headers, lists, and code blocks
4. Make it scannable and easy to read
"""

from ...domain.ports import FormattingPort
from ...domain.models import StructuredAnswer


class MarkdownFormatter(FormattingPort):
    """
    Formats structured answers as markdown.

    Example usage:
        formatter = MarkdownFormatter()
        answer = StructuredAnswer(reasoning="...", conclusion="...")
        markdown = formatter.format(answer)
    """

    def __init__(self, include_metadata: bool = True):
        """
        Initialize the Markdown Formatter.

        Args:
            include_metadata: Whether to include metadata in output
        """
        self.include_metadata = include_metadata

    def format(self, answer: StructuredAnswer) -> str:
        """
        Format a structured answer as markdown.

        Args:
            answer: The structured answer to format

        Returns:
            Markdown-formatted string
        """
        # TODO: Implement markdown formatting
        #
        # Steps:
        # 1. Create a markdown document structure
        # 2. Add title/header
        # 3. Format the reasoning section
        # 4. Format the conclusion
        # 5. Add citations and sources
        # 6. Include metadata (optional)
        # 7. Make it visually appealing with proper spacing

        # Placeholder implementation:
        output = "# Answer\n\n"
        output += f"{answer.conclusion}\n"

        # Example implementation:
        # # Start with a header
        # output = "# Research Answer\n\n"
        #
        # # Add confidence indicator if available
        # if self.include_metadata and 'confidence' in answer.metadata:
        #     confidence = answer.metadata['confidence']
        #     confidence_pct = f"{confidence:.0%}"
        #     confidence_emoji = "=â" if confidence > 0.7 else "=á" if confidence > 0.4 else "=4"
        #     output += f"**Confidence**: {confidence_emoji} {confidence_pct}\n\n"
        #     output += "---\n\n"
        #
        # # Add the main conclusion
        # output += "## Summary\n\n"
        # output += f"{answer.conclusion}\n\n"
        #
        # # Add reasoning/explanation
        # if answer.reasoning:
        #     output += "## How We Got Here\n\n"
        #     # If reasoning has multiple steps, format as list
        #     reasoning_lines = answer.reasoning.strip().split('\n')
        #     if len(reasoning_lines) > 1:
        #         for line in reasoning_lines:
        #             if line.strip():
        #                 output += f"- {line.strip()}\n"
        #         output += "\n"
        #     else:
        #         output += f"{answer.reasoning}\n\n"
        #
        # # Add sources/citations
        # if self.include_metadata and 'sources' in answer.metadata:
        #     output += "## Sources\n\n"
        #     sources = answer.metadata['sources']
        #     for i, source in enumerate(sources, 1):
        #         title = source.get('title', 'Source')
        #         url = source.get('url', '#')
        #         provider = source.get('provider', 'Unknown')
        #         output += f"{i}. [{title}]({url}) *({provider})*\n"
        #     output += "\n"
        #
        # # Add metadata section (optional)
        # if self.include_metadata:
        #     metadata_to_show = {
        #         k: v for k, v in answer.metadata.items()
        #         if k not in ['sources', 'confidence'] and v is not None
        #     }
        #     if metadata_to_show:
        #         output += "---\n\n"
        #         output += "<details>\n<summary>Additional Information</summary>\n\n"
        #         for key, value in metadata_to_show.items():
        #             output += f"- **{key.replace('_', ' ').title()}**: {value}\n"
        #         output += "\n</details>\n"
        #
        # # Add footer
        # output += "\n---\n\n"
        # output += "*Generated by TeraFinder*\n"

        return output


# HELPFUL RESOURCES:
# - Markdown Guide: https://www.markdownguide.org/
# - GitHub Flavored Markdown: https://github.github.com/gfm/
# - Markdown cheat sheet: https://www.markdownguide.org/cheat-sheet/
#
# TIPS:
# - Use proper heading hierarchy (# ## ###)
# - Add horizontal rules (---) for visual separation
# - Use blockquotes (>) for important callouts
# - Format code with backticks or code blocks
# - Make links descriptive, not just URLs
# - Use tables for structured data
# - Add emojis sparingly for visual cues
# - Test rendering in different markdown viewers
# - Consider accessibility (screen readers)
# - Keep line lengths reasonable for readability
